### ISSUE TITLE
License for commercial use

### ISSUE THREAD

**Issue by larsbrinkhoff** [larsbrinkhoff/lbForth#30]
@vigilancetech-com has expressed interest in using lbForth to build commercial software.

**Comment by vigilancetech-com** [comment]
for example, see under licensing here:

http://pfe.sourceforge.net/

**Comment by larsbrinkhoff** [comment]
I have thought about this, and for now, I'm not inclined to change to another license.  I chose GPL because I don't want to give away my work for commercial use.

However, I'm not adverse to license the software under other terms, in return for a modest fee.

**Comment by ruv** [comment]
@larsbrinkhoff, by the way, you don't need to **change** the license. You can just add another one (and provide your product in [multi-licensing](https://en.wikipedia.org/wiki/Multi-licensing) manner).  Also, as author, you can give any special license for any special customer.

**Comment by larsbrinkhoff** [comment]
Right, I had something like that in mind.

**Comment by vigilancetech-com** [comment]
Well, the issue would then become that if you accept patches from others who are expecting it to be GPL you would need to get advanced permission from all contributors to license it for commercial use, whereas if you license it LGPL everyone knows up front that it can be used commercially.   What you may consider is to put a GPL type restriction if it is to be used commercially as a program development environment.

Naturally, for example, someone shouldn't be able to use it as a base for a commercial Forth IDE without compensating its developers, but if someone wants to develop a piece of consumer software all you are really accomplishing is to drive people to use other Forths for that instead, and then any patches/upgrades/fixes will be contributed back to those rather than yours.   Generally devs who produce consumer applications have no interest in hoarding enhancements to the development environment itself because the chances of anyone using those enhancements to directly complete with their projects are slim to none.

**Comment by ruv** [comment]
Usually, authors of the compilers proved some way to use a target code without any restriction (i.e., under its own license). For example, [GCC has exception](https://gcc.gnu.org/onlinedocs/libstdc++/manual/license.html) in GPLv3 for runtime library, [VFX Forth implies](http://www.mpeforth.com/software/pc-systems/licensing-and-other-matters/) custom license and royalty if end-user has access to the interpreter.

For a Forth system, GPL without exceptions doesn't allow to distribute a target code (or end-user software) under other terms than GPL, if any part of the source Forth system (or its derivative) is presenced in the target software.

LGPL is something like GPL with some exceptions: a target software can have any license but any distributed part of the source Forth system (or its derivative) must be covered by LGPL.

**Comment by ruv** [comment]
>  I chose GPL because I don't want to give away my work for commercial use.

By the way, GPL doesn't prohibit commercial use of a software. For example, you can:
1. use the software on the server side, without distribution and get profit by providing some service (AGPL covered this case),
2. selling hardware devices with the software (tivoization issue was covered by GPLv3),
3. selling technical support for the software,
4. even selling the software itself, but you can't restrict distribution of the sold copies, so it has less sense.

Citation from GPLv3: "You may charge any price or no price for each copy that you convey, and you may offer support or warranty protection for a fee"

**Comment by larsbrinkhoff** [comment]
For now, I will stay with GPL, with an option to do a special commercial license if there's an interest.

By all means, use lbForth for whatever purpuse within the limits of the GPL.

I may be open to reconsider and change to LGPL in the future.  Right now, I don't see the benefit.  One thing that could sway my mind is if there's a large enough body of contributions from other people.

**Comment by vigilancetech-com** [comment]
how much were you thinking about for a commercial license?

**Comment by larsbrinkhoff** [comment]
I was thinking something quite modest like $50.

**Comment by larsbrinkhoff** [comment]
I think this issue has settled.
